### ISSUE TITLE
Updater constantly finds new versions of persistence-1.0-SNAPSHOT.jar

### ISSUE THREAD

**Issue by amki** [xpdota/event-trigger#242]
Whenever I use triggevent-upd.exe it finds new updates to deps/persistence-1.0-SNAPSHOT.jar but can't actually load the PersistenceProdiver then.

It rotates what I assume to be the local hashes of the file and the file seems to have content in it but it only works after a lot of trys.
```
You should report this as a bug and include log files in C:\Users\amki.AD\AppData\Roaming\triggevent as well as this error message.

You can also try moving/renaming the properties files in that directory to see if this error is being caused by a problem with your settings.

Also, try updating using the button below.

java.lang.NoClassDefFoundError: gg/xp/xivsupport/persistence/PersistenceProvider
	at gg.xp.xivsupport.gui.GuiMain.lambda$main$0(GuiMain.java:138)
	at gg.xp.xivsupport.gui.util.CatchFatalError.run(CatchFatalError.java:23)
	at gg.xp.xivsupport.gui.GuiMain.main(GuiMain.java:134)
	at gg.xp.xivsupport.gui.GuiLaunch.main(GuiLaunch.java:8)
Caused by: java.lang.ClassNotFoundException: gg.xp.xivsupport.persistence.PersistenceProvider
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 4 more
```

triggevent-upd.exe:

```
Install dir: G:\Downloads\triggevent
Starting update check...
Beginning update check. If this hangs, freezes, or crashes, check that your AV is not interfering.
Properties file exists, loading it...
Branch not specified in properties file, assuming default of stable
URL not specified in properties file, assuming default of https://xpdota.github.io/event-trigger/%s/v2/%s
Using branch: stable
Using URL template: https://xpdota.github.io/event-trigger/%s/v2/%s
Checking for Triggevent updates...
Hashing Local Files...
Calculating update...
8c79eba0445fdc5f7afa1df3a8b40fa7 == 8c79eba0445fdc5f7afa1df3a8b40fa7 Triggevent_Stub.dll
8a2f8c473c9a8548dc307d040fabcf2e == 8a2f8c473c9a8548dc307d040fabcf2e deps/Java-WebSocket-1.5.2.jar
b9e19f96299334e586775e57c0f0037e == b9e19f96299334e586775e57c0f0037e deps/actimport-1.0-SNAPSHOT.jar
8484cd17d040d837983323f760b2c660 == 8484cd17d040d837983323f760b2c660 deps/annotations-23.0.0.jar
7aa86dc0c185691ebfedf507cd02f0bf == 7aa86dc0c185691ebfedf507cd02f0bf deps/caffeine-2.9.2.jar
6d4e6fd385da16b9418a5ff9170aa3bd == 6d4e6fd385da16b9418a5ff9170aa3bd deps/caffeine-api-2.9.2-29.v717aac953ff3.jar
177abb28e73894dd79e6f5b19ac98912 == 177abb28e73894dd79e6f5b19ac98912 deps/cd-tracker-1.0-SNAPSHOT.jar
07dc532ee316fe1f2f0323e9bd2f8df4 == 07dc532ee316fe1f2f0323e9bd2f8df4 deps/commons-beanutils-1.9.4.jar
567159b1ae257a43e1391a8f59d24cfe == 567159b1ae257a43e1391a8f59d24cfe deps/commons-codec-1.11.jar
f54a8510f834a1a57166970bfc982e94 == f54a8510f834a1a57166970bfc982e94 deps/commons-collections-3.2.2.jar
4a37023740719b391f10030362c86be6 == 4a37023740719b391f10030362c86be6 deps/commons-collections4-4.4.jar
3b4b7ccfaeceeac240b804839ee1a1ca == 3b4b7ccfaeceeac240b804839ee1a1ca deps/commons-io-2.11.0.jar
19fe50567358922bdad277959ea69545 == 19fe50567358922bdad277959ea69545 deps/commons-lang3-3.12.0.jar
040b4b4d8eac886f6b4a2a3bd2f31b00 == 040b4b4d8eac886f6b4a2a3bd2f31b00 deps/commons-logging-1.2.jar
c1c130c369aa86bfe4f7a7a920bc0223 == c1c130c369aa86bfe4f7a7a920bc0223 deps/commons-text-1.9.jar
bc8a63a2f04f8922f08b7ed36855e5ca == bc8a63a2f04f8922f08b7ed36855e5ca deps/custom-party-overlay-1.0-SNAPSHOT.jar
a89d22f4802437651cbb40b76125a529 == a89d22f4802437651cbb40b76125a529 deps/dot-tracker-1.0-SNAPSHOT.jar
bfe6f179ceb728cbdf40770065537229 == bfe6f179ceb728cbdf40770065537229 deps/easytriggers-1.0-SNAPSHOT.jar
655814242aa5fa27b4f4eaca9390c951 == 655814242aa5fa27b4f4eaca9390c951 deps/flatlaf-1.6.5.jar
1125469744b5b7b9f404832279633442 == 1125469744b5b7b9f404832279633442 deps/groovy-3.0.10.jar
d42b8855e3b7e4f3506ffc0b5b85d149 == d42b8855e3b7e4f3506ffc0b5b85d149 deps/groovy-sandbox-1.27.jar
057ceb615fe7b56b65d00aa315b768a1 == 057ceb615fe7b56b65d00aa315b768a1 deps/groovy-sandboxing-1.0-SNAPSHOT.jar
40d6b9075fbd28fa10292a45a0db9457 == 40d6b9075fbd28fa10292a45a0db9457 deps/httpclient-4.5.13.jar
e07a248f61c52776a2366c075dcd4963 == e07a248f61c52776a2366c075dcd4963 deps/httpcore-4.4.13.jar
3f0c1ef2c9dc47b62b780192f54b0c18 == 3f0c1ef2c9dc47b62b780192f54b0c18 deps/httpmime-4.5.13.jar
2352a291fc39d23cfe5c100728de1ea7 == 2352a291fc39d23cfe5c100728de1ea7 deps/jackson-annotations-2.13.2.jar
c56433d75479665998ccbd50678480fa == c56433d75479665998ccbd50678480fa deps/jackson-core-2.13.2.jar
b66a191219300cdb6113af6a6360326d == b66a191219300cdb6113af6a6360326d deps/jackson-databind-2.13.2.1.jar
7693a537daa6acd34cc6da0a4a3dc2da == 7693a537daa6acd34cc6da0a4a3dc2da deps/jackson-datatype-jdk8-2.13.2.jar
1a2dd8c76321cef26cc2669fe70a2557 == 1a2dd8c76321cef26cc2669fe70a2557 deps/javassist-3.28.0-GA.jar
2b884b01ad2f62d4f5dd11387a8bf799 == 2b884b01ad2f62d4f5dd11387a8bf799 deps/jna-5.10.0.jar
c1ab841070c388ec32b77cdc05f084fb == c1ab841070c388ec32b77cdc05f084fb deps/jna-platform-5.10.0.jar
9d9576fc366854c32f4d1daf9dcc4b1c == 9d9576fc366854c32f4d1daf9dcc4b1c deps/job-overlays-1.0-SNAPSHOT.jar
dd83accb899363c32b07d7a1b2e4ce40 == dd83accb899363c32b07d7a1b2e4ce40 deps/jsr305-3.0.2.jar
a6e6ff60516bfe2cc06d2c487709b744 == a6e6ff60516bfe2cc06d2c487709b744 deps/launcher-1.0-SNAPSHOT.jar
196b120a3c9f01a5b9b2ed5220359963 == 196b120a3c9f01a5b9b2ed5220359963 deps/logback-classic-1.2.6.jar
b1930b5651377477a06ade2319f70dfc == b1930b5651377477a06ade2319f70dfc deps/logback-core-1.2.6.jar
29418013eb2b66fbf9bcd48a2dcd7543 == 29418013eb2b66fbf9bcd48a2dcd7543 deps/opencsv-5.6.jar
85511347fbd7d0d38a349c6ecdbd2ce5 -> 93a4989b1ab3f15c6a55a8a37e716030 deps/persistence-1.0-SNAPSHOT.jar
b379db6e4ee67fd2d731faadc3a5afa5 == b379db6e4ee67fd2d731faadc3a5afa5 deps/personal-cast-bar-overlay-1.0-SNAPSHOT.jar
462404f92bdbd710aa2abf6fc1168247 == 462404f92bdbd710aa2abf6fc1168247 deps/picocontainer-2.15.jar
83db6d45f3ab7ab2a00c51f42e1c0726 == 83db6d45f3ab7ab2a00c51f42e1c0726 deps/reevent-1.0-SNAPSHOT.jar
1d0070839d825f57fe6f4d8e2a82989b == 1d0070839d825f57fe6f4d8e2a82989b deps/reflections-0.10.2.jar
9c3b7321b1be9dc1dbac775ffbc76d7c == 9c3b7321b1be9dc1dbac775ffbc76d7c deps/skill-hit-overlay-1.0-SNAPSHOT.jar
fbcf58513bc25b80f075d812aad3e3cf == fbcf58513bc25b80f075d812aad3e3cf deps/slf4j-api-1.7.32.jar
55d0d3398a0e33b65eefd0b10c01aecb == 55d0d3398a0e33b65eefd0b10c01aecb deps/telesto-support-1.0-SNAPSHOT.jar
fdea299f149d207116bf3e25dd10c227 == fdea299f149d207116bf3e25dd10c227 deps/timelines-1.0-SNAPSHOT.jar
8b1e6f9016b5c091131ed0f2c83b6bcd == 8b1e6f9016b5c091131ed0f2c83b6bcd deps/titan-jails-1.0-SNAPSHOT.jar
517c19f9eca8eb78a2d5acd7853511dd == 517c19f9eca8eb78a2d5acd7853511dd deps/trigger-support-1.0-SNAPSHOT.jar
7a7f388c6d2bcc459a9b6944cb357426 == 7a7f388c6d2bcc459a9b6944cb357426 deps/triggers-ew-1.0-SNAPSHOT.jar
a79006557cc3031a9dc2aedddfed0969 == a79006557cc3031a9dc2aedddfed0969 deps/triggers-general-1.0-SNAPSHOT.jar
94400a6061f459a2910df316b5ee80bf == 94400a6061f459a2910df316b5ee80bf deps/triggers-sb-1.0-SNAPSHOT.jar
9b647cf0156592b064fe61f9b84a3257 == 9b647cf0156592b064fe61f9b84a3257 deps/xivdata-1.0-SNAPSHOT.jar
efcd93660859a7beb1b16cf966d0bea9 == efcd93660859a7beb1b16cf966d0bea9 deps/xivsupport-1.0-SNAPSHOT.jar
68a65629922185fc81959bb500974184 == 68a65629922185fc81959bb500974184 triggevent-import.exe
1a7656c807b1b20fbf9dfafff7ce1b66 == 1a7656c807b1b20fbf9dfafff7ce1b66 triggevent.exe
Updating 1 files...
Downloading 1 / 1 (deps/persistence-1.0-SNAPSHOT.jar)
Done downloading files
Update finished! 1 files needed to be updated.
```

These were the last 3 hashes until it finally worked:

4aab9b1dd7bde69f6cd08fa77b99ebb5 -> 93a4989b1ab3f15c6a55a8a37e716030 deps/persistence-1.0-SNAPSHOT.jar
53e66b31d729d072a40c7f2ad0982564 -> 93a4989b1ab3f15c6a55a8a37e716030 deps/persistence-1.0-SNAPSHOT.jar
85511347fbd7d0d38a349c6ecdbd2ce5 -> 93a4989b1ab3f15c6a55a8a37e716030 deps/persistence-1.0-SNAPSHOT.jar

**Comment by xpdota** [comment]
Hmm, I suspect something is messing with your download. The persistence jar never had those hashes, so it doesn't seem to be downloading the wrong file or anything like that. Could be an error page?

If it happens again, would you mind attaching one of the bad files?

**Comment by amki** [comment]
I can pretty much provoke this at will by deleting the corresponding jar from the deps folder.

Same error, this is the downloaded jar 
[persistence-1.0-SNAPSHOT.jar.zip](https://github.com/xpdota/event-trigger/files/10471309/persistence-1.0-SNAPSHOT.jar.zip) )I had to zip it because GitHub won't take jars...)

Looks like a valid jar to me but I haven't really used java in quite a while.

Loading this gives the same error

```
You should report this as a bug and include log files in C:\Users\amki.AD\AppData\Roaming\triggevent as well as this error message.

You can also try moving/renaming the properties files in that directory to see if this error is being caused by a problem with your settings.

Also, try updating using the button below.

java.lang.NoClassDefFoundError: gg/xp/xivsupport/persistence/PersistenceProvider
	at gg.xp.xivsupport.gui.GuiMain.lambda$main$0(GuiMain.java:138)
	at gg.xp.xivsupport.gui.util.CatchFatalError.run(CatchFatalError.java:23)
	at gg.xp.xivsupport.gui.GuiMain.main(GuiMain.java:134)
	at gg.xp.xivsupport.gui.GuiLaunch.main(GuiLaunch.java:8)
Caused by: java.lang.ClassNotFoundException: gg.xp.xivsupport.persistence.PersistenceProvider
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 4 more
```

**Comment by xpdota** [comment]
Hmmm, your jar is missing a lot of files (good copy on left, yours on the right):

![image](https://user-images.githubusercontent.com/14287379/213839777-3a6ee295-12e9-4b5a-8821-177a7b27aa99.png)

Antivirus maybe? It's downloading via https, so it probably isn't something network-related. 

If you try to manually download [the file](https://xpdota.github.io/event-trigger/stable/v2/deps/persistence-1.0-SNAPSHOT.jar), how big is the resulting download?

**Comment by amki** [comment]
When I use this link I get 46902bytes with md5 93a4989b1ab3f15c6a55a8a37e716030 *persistence-1.0-SNAPSHOT.jar, triggevent-upd.exe fetched something else with md5 b2926c883cdf9153f2e041259479e04f and another call to triggevent-upd.exe fixed it and fetched the correct file.

**Comment by amki** [comment]
I've made a new observation after today's update. All the jars download successfully but the last one (which ever that may be) is having problems. I've seen the same problems with triggers-ew-1.0-SNAPSHOT.jar as well...
